// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace OverviewServicePlugin;

#nullable enable

public class AreaDto
{
    [JsonPropertyName("phaseID")]
    public int PhaseId { get; set; }

    [JsonPropertyName("area")]
    public string? Area { get; set; }

    [JsonPropertyName("areaID")]
    public int AreaId { get; set; }

    [JsonPropertyName("owner")]
    public string? Owner { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("testInstructions")]
    public string? TestInstructions { get; set; }

    [JsonPropertyName("status")]
    public int? Status { get; set; }

    [JsonPropertyName("note")]
    public string? Note { get; set; }

    [JsonPropertyName("release")]
    public int Release { get; set; }

    [JsonPropertyName("statusSetUser")]
    public string? StatusSetUser { get; set; }

    [JsonPropertyName("ovStatusID")]
    public int? OvStatusId { get; set; }

    [JsonPropertyName("statusSetDate")]
    public DateTime? StatusSetDate { get; set; }

    [JsonPropertyName("ovStatusSetUser")]
    public string? OvStatusSetUser { get; set; }

    [JsonPropertyName("ovStatusSetDate")]
    public DateTime? OvStatusSetDate { get; set; }

    [JsonPropertyName("components")]
    public List<ComponentDto>? Components { get; set; }

    [JsonPropertyName("tag")]
    public int? Tag { get; set; }

    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("weight")]
    public int? Weight { get; set; }

    [JsonPropertyName("sysmanRef")]
    public long? SysmanRef { get; set; }

    [JsonPropertyName("fromSysman")]
    public bool FromSysman { get; set; }

    [JsonPropertyName("sysmanType")]
    public string? SysmanType { get; set; }

    [JsonPropertyName("template")]
    public string? Template { get; set; }

    [JsonPropertyName("testLeader")]
    public string? TestLeader { get; set; }

    [JsonPropertyName("tagName")]
    public string? TagName { get; set; }

    [JsonPropertyName("computer")]
    public string? Computer { get; set; }

    [JsonPropertyName("responsibleFromTag")]
    public string? ResponsibleFromTag { get; set; }

    [JsonPropertyName("phaseName")]
    public string? PhaseName { get; set; }

    [JsonPropertyName("notes")]
    public List<OvlogRun>? Notes { get; set; }

    [JsonPropertyName("noteID")]
    public Guid NoteId { get; set; }

    [JsonPropertyName("statusExpireDate")]
    public DateTime? StatusExpireDate { get; set; }

    [JsonPropertyName("milestone")]
    public bool? Milestone { get; set; }

    [JsonPropertyName("haveParent")]
    public bool? HaveParent { get; set; }

    [JsonPropertyName("parentAreaID")]
    public int? ParentAreaId { get; set; }

    [JsonPropertyName("selectedRelease")]
    public List<int>? SelectedRelease { get; set; }

}

public class ClientDto
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("targetID")]
    public long TargetId { get; set; }

    [JsonPropertyName("model")]
    public string? Model { get; set; }

    [JsonPropertyName("osname")]
    public string? Osname { get; set; }

    [JsonPropertyName("releaseReady")]
    public bool ReleaseReady { get; set; }

    [JsonPropertyName("hwID")]
    public long? HwId { get; set; }

    [JsonPropertyName("owner")]
    public string? Owner { get; set; }

    [JsonPropertyName("location")]
    public string? Location { get; set; }

    [JsonPropertyName("department")]
    public string? Department { get; set; }

    [JsonPropertyName("costCenter")]
    public string? CostCenter { get; set; }

    [JsonPropertyName("procureDate")]
    public DateTime? ProcureDate { get; set; }

    [JsonPropertyName("planId")]
    public long? PlanId { get; set; }

    [JsonPropertyName("planName")]
    public string? PlanName { get; set; }

    [JsonPropertyName("planStatus")]
    public string? PlanStatus { get; set; }

    [JsonPropertyName("systemsApproved")]
    public int SystemsApproved { get; set; }

    [JsonPropertyName("systemsUnApproved")]
    public int SystemsUnApproved { get; set; }

    [JsonPropertyName("systemsTotal")]
    public int SystemsTotal { get; set; }

    [JsonPropertyName("systems")]
    public List<SystemDto>? Systems { get; set; }

    [JsonPropertyName("isSpecial")]
    public bool? IsSpecial { get; set; }

    [JsonPropertyName("tag")]
    public string? Tag { get; set; }

    [JsonPropertyName("generalDescription")]
    public string? GeneralDescription { get; set; }

    [JsonPropertyName("deploymentID")]
    public int? DeploymentId { get; set; }

}

public class ClientDtoDataPage
{
    [JsonPropertyName("count")]
    public int Count { get; set; }

    [JsonPropertyName("data")]
    public List<ClientDto>? Data { get; set; }

}

public class ComponentDto
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("releaseID")]
    public int ReleaseId { get; set; }

    [JsonPropertyName("componentID")]
    public int ComponentId { get; set; }

    [JsonPropertyName("areaID")]
    public int AreaId { get; set; }

    [JsonPropertyName("owner")]
    public string? Owner { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("testInstructions")]
    public string? TestInstructions { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    [JsonPropertyName("computer")]
    public string? Computer { get; set; }

    [JsonPropertyName("filePath")]
    public string? FilePath { get; set; }

    [JsonPropertyName("testers")]
    public List<TestersDto>? Testers { get; set; }

    [JsonPropertyName("template")]
    public string? Template { get; set; }

}

public class ComponentTemplateDto
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("phaseID")]
    public int PhaseId { get; set; }

    [JsonPropertyName("releaseID")]
    public int ReleaseId { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("testInstructions")]
    public string? TestInstructions { get; set; }

}

public class DiagClientSysVConpareSysX
{
    [JsonPropertyName("systemName")]
    public string? SystemName { get; set; }

    [JsonPropertyName("count")]
    public int Count { get; set; }

}

public class DiagClientSysVConpareSysXDataPage
{
    [JsonPropertyName("count")]
    public int Count { get; set; }

    [JsonPropertyName("data")]
    public List<DiagClientSysVConpareSysX>? Data { get; set; }

}

public class MailDto
{
    [JsonPropertyName("port")]
    public int Port { get; set; }

    [JsonPropertyName("fromAdress")]
    public string? FromAdress { get; set; }

    [JsonPropertyName("userName")]
    public string? UserName { get; set; }

    [JsonPropertyName("password")]
    public string? Password { get; set; }

    [JsonPropertyName("smtpServer")]
    public string? SmtpServer { get; set; }

}

public class MailFromSyncDto
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("body")]
    public string? Body { get; set; }

    [JsonPropertyName("test")]
    public string? Test { get; set; }

    [JsonPropertyName("area")]
    public string? Area { get; set; }

    [JsonPropertyName("userMail")]
    public string? UserMail { get; set; }

}

public class NewPlan
{
    [JsonPropertyName("shortName")]
    public string? ShortName { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    [JsonPropertyName("planner")]
    public string? Planner { get; set; }

    [JsonPropertyName("responsible")]
    public string? Responsible { get; set; }

    [JsonPropertyName("category")]
    public string? Category { get; set; }

    [JsonPropertyName("releaseID")]
    public int ReleaseId { get; set; }

}

public class OVTags
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("ovTagsRights")]
    public List<OVTagsRights>? OvTagsRights { get; set; }

}

public class OVTagsRights
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("ovTagID")]
    public int OvTagId { get; set; }

    [JsonPropertyName("adGroupName")]
    public string? AdGroupName { get; set; }

    [JsonPropertyName("adGroupSID")]
    public string? AdGroupSid { get; set; }

    [JsonPropertyName("ovTag")]
    public OVTags OvTag { get; set; }

}

public class OvlogRun
{
    [JsonPropertyName("releaseId")]
    public int ReleaseId { get; set; }

    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("note")]
    public string? Note { get; set; }

    [JsonPropertyName("date")]
    public DateTime? Date { get; set; }

    [JsonPropertyName("release")]
    public int? Release { get; set; }

    [JsonPropertyName("userId")]
    public string? UserId { get; set; }

    [JsonPropertyName("noteId")]
    public Guid NoteId { get; set; }

}

public class PlanDto
{
    [JsonPropertyName("planId")]
    public long PlanId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("scheduleDate")]
    public string? ScheduleDate { get; set; }

    [JsonPropertyName("planner")]
    public string? Planner { get; set; }

    [JsonPropertyName("planApprover")]
    public string? PlanApprover { get; set; }

    [JsonPropertyName("planStatus")]
    public string? PlanStatus { get; set; }

    [JsonPropertyName("comment")]
    public string? Comment { get; set; }

    [JsonPropertyName("updateDate")]
    public string? UpdateDate { get; set; }

    [JsonPropertyName("createDate")]
    public string? CreateDate { get; set; }

    [JsonPropertyName("planCategory")]
    public string? PlanCategory { get; set; }

    [JsonPropertyName("operatingSystem")]
    public string? OperatingSystem { get; set; }

    [JsonPropertyName("clients")]
    public List<ClientDto>? Clients { get; set; }

    [JsonPropertyName("numberOfClients")]
    public int NumberOfClients { get; set; }

    [JsonPropertyName("releaseID")]
    public int? ReleaseId { get; set; }

    [JsonPropertyName("windowsName")]
    public string? WindowsName { get; set; }

}

public class ReleaseversionDto
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("releaseName")]
    public string? ReleaseName { get; set; }

    [JsonPropertyName("technicalReleaseId")]
    public int TechnicalReleaseId { get; set; }

    [JsonPropertyName("releaseResponsible")]
    public string? ReleaseResponsible { get; set; }

    [JsonPropertyName("comment")]
    public string? Comment { get; set; }

    [JsonPropertyName("abnormalities")]
    public string? Abnormalities { get; set; }

    [JsonPropertyName("createdDate")]
    public DateTime CreatedDate { get; set; }

    [JsonPropertyName("finishedDate")]
    public DateTime? FinishedDate { get; set; }

    [JsonPropertyName("status")]
    public int? Status { get; set; }

    [JsonPropertyName("statusSetUser")]
    public string? StatusSetUser { get; set; }

    [JsonPropertyName("statusSetDate")]
    public DateTime? StatusSetDate { get; set; }

    [JsonPropertyName("sysmanOSID")]
    public int? SysmanOsid { get; set; }

    [JsonPropertyName("windowsName")]
    public string? WindowsName { get; set; }

}

public class SlimPhaseRunDto
{
    [JsonPropertyName("releaseID")]
    public int ReleaseId { get; set; }

    [JsonPropertyName("phaseId")]
    public int PhaseId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("owner")]
    public string? Owner { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    [JsonPropertyName("statusSetUser")]
    public string? StatusSetUser { get; set; }

    [JsonPropertyName("statusDate")]
    public DateTime StatusDate { get; set; }

    [JsonPropertyName("phaseStatusUser")]
    public string? PhaseStatusUser { get; set; }

    [JsonPropertyName("phaseStatusDate")]
    public DateTime PhaseStatusDate { get; set; }

    [JsonPropertyName("icon")]
    public string? Icon { get; set; }

    [JsonPropertyName("order")]
    public int? Order { get; set; }

}

public class SystemDto
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("status")]
    public int? Status { get; set; }

    [JsonPropertyName("systemID")]
    public long? SystemId { get; set; }

    [JsonPropertyName("releaseID")]
    public int ReleaseId { get; set; }

    [JsonPropertyName("totalClients")]
    public int TotalClients { get; set; }

    [JsonPropertyName("totalInstalledClients")]
    public int TotalInstalledClients { get; set; }

    [JsonPropertyName("applicationCount")]
    public int ApplicationCount { get; set; }

    [JsonPropertyName("applicationNotWin10Ready")]
    public int ApplicationNotWin10Ready { get; set; }

    [JsonPropertyName("applicationIsWin10Ready")]
    public int ApplicationIsWin10Ready { get; set; }

    [JsonPropertyName("ignore")]
    public bool? Ignore { get; set; }

    [JsonPropertyName("weight")]
    public int? Weight { get; set; }

}

public class TestersDto
{
    [JsonPropertyName("testID")]
    public int TestId { get; set; }

    [JsonPropertyName("componentID")]
    public int ComponentId { get; set; }

    [JsonPropertyName("tester")]
    public string? Tester { get; set; }

    [JsonPropertyName("computer")]
    public string? Computer { get; set; }

    [JsonPropertyName("operatingsystemID")]
    public int OperatingsystemId { get; set; }

    [JsonPropertyName("status")]
    public int Status { get; set; }

    [JsonPropertyName("note")]
    public List<OvlogRun>? Note { get; set; }

    [JsonPropertyName("filePath")]
    public string? FilePath { get; set; }

    [JsonPropertyName("statusFriendlyName")]
    public string? StatusFriendlyName { get; set; }

    [JsonPropertyName("statusDate")]
    public DateTime? StatusDate { get; set; }

    [JsonPropertyName("weight")]
    public int? Weight { get; set; }

    [JsonPropertyName("template")]
    public string? Template { get; set; }

    [JsonPropertyName("id")]
    public int Id { get; set; }

}

public class OverviewVersion
{
    [JsonPropertyName("version")]
    public string? Version { get; set; }

}


